In [22]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv("Combined MM_Data.csv") 
df

,0,Q_VFD1_Temperature,Q_VFD2_Temperature,Q_VFD3_Temperature,Q_VFD4_Temperature,M_Conv1_Speed_mmps,M_Conv2_Speed_mmps,M_Conv3_Speed_mmps,M_Conv4_Speed_mmps,I_R01_Gripper_Pot,...,M_R04_UJointAngle_Degree,M_R04_RJointAngle_Degree,M_R04_BJointAngle_Degree,M_R04_TJointAngle_Degree,I_SafetyDoor1_Status,I_SafetyDoor2_Status,Q_Cell_CycleCount,I_MHS_GreenRocketTray,Cam1,Cam2
0,2023-12-11 11:50:52.119915,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5269,...,0.010986,-0.001172,-0.004120,0.004302,True,True,1,True,Dataset/BATCH1000/000000_0.png,Dataset/BATCH1000/000000_1.png
1,2023-12-11 11:50:52.483993,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5277,...,0.010986,-0.001172,-0.004120,0.004302,True,True,1,True,Dataset/BATCH1000/000001_0.png,Dataset/BATCH1000/000001_1.png
2,2023-12-11 11:50:52.814902,73.130005,72.130020,73.130020,73.363525,111,83,111,111,4914,...,0.010986,-0.001172,-0.004120,0.004302,True,True,1,True,Dataset/BATCH1000/000002_0.png,Dataset/BATCH1000/000002_1.png
3,2023-12-11 11:50:53.210953,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5235,...,0.010986,-0.001172,-0.004120,0.004302,True,True,1,True,Dataset/BATCH1000/000003_0.png,Dataset/BATCH1000/000003_1.png
4,2023-12-11 11:50:53.554022,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5311,...,0.010986,-0.001172,-0.004120,0.004302,True,True,1,True,Dataset/BATCH1000/000004_0.png,Dataset/BATCH1000/000004_1.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165996,2023-12-12 11:25:40.344616,88.130219,86.130241,87.630241,87.986328,111,111,111,111,11198,...,0.786621,0.000000,-0.005493,0.000000,True,True,255,True,Dataset/BATCH166000/165996_0.png,Dataset/BATCH166000/165996_1.png
165997,2023-12-12 11:25:40.828360,88.130219,86.130241,87.630241,87.975342,111,111,111,111,11189,...,0.786621,0.000000,-0.005493,0.000000,True,True,255,True,Dataset/BATCH166000/165997_0.png,Dataset/BATCH166000/165997_1.png
165998,2023-12-12 11:25:41.347278,88.130219,86.130241,87.630241,87.964355,111,111,111,111,11249,...,0.786621,0.000000,-0.005493,0.000000,True,True,255,True,Dataset/BATCH166000/165998_0.png,Dataset/BATCH166000/165998_1.png
165999,2023-12-12 11:25:41.871513,88.130219,86.130241,87.630241,87.953369,111,111,111,111,11215,...,0.786621,0.000000,-0.005493,0.000000,True,True,255,True,Dataset/BATCH166000/165999_0.png,Dataset/BATCH166000/165999_1.png
166000,2023-12-12 11:25:42.410629,88.130219,86.130241,87.630241,87.942383,111,111,111,111,11240,...,0.786621,0.000000,-0.005493,0.000000,True,True,255,True,Dataset/BATCH166000/166000_0.png,Dataset/BATCH166000/166000_1.png

In [42]:
df = df.rename(columns={'0': 'time'})
df

,time,Q_VFD1_Temperature,Q_VFD2_Temperature,Q_VFD3_Temperature,Q_VFD4_Temperature,M_Conv1_Speed_mmps,M_Conv2_Speed_mmps,M_Conv3_Speed_mmps,M_Conv4_Speed_mmps,I_R01_Gripper_Pot,...,M_R04_UJointAngle_Degree,M_R04_RJointAngle_Degree,M_R04_BJointAngle_Degree,M_R04_TJointAngle_Degree,I_SafetyDoor1_Status,I_SafetyDoor2_Status,Q_Cell_CycleCount,I_MHS_GreenRocketTray,Cam1,Cam2
0,2023-12-11 11:50:52.119915,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5269,...,0.010986,-0.001172,-0.004120,0.004302,True,True,1,True,Dataset/BATCH1000/000000_0.png,Dataset/BATCH1000/000000_1.png
1,2023-12-11 11:50:52.483993,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5277,...,0.010986,-0.001172,-0.004120,0.004302,True,True,1,True,Dataset/BATCH1000/000001_0.png,Dataset/BATCH1000/000001_1.png
2,2023-12-11 11:50:52.814902,73.130005,72.130020,73.130020,73.363525,111,83,111,111,4914,...,0.010986,-0.001172,-0.004120,0.004302,True,True,1,True,Dataset/BATCH1000/000002_0.png,Dataset/BATCH1000/000002_1.png
3,2023-12-11 11:50:53.210953,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5235,...,0.010986,-0.001172,-0.004120,0.004302,True,True,1,True,Dataset/BATCH1000/000003_0.png,Dataset/BATCH1000/000003_1.png
4,2023-12-11 11:50:53.554022,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5311,...,0.010986,-0.001172,-0.004120,0.004302,True,True,1,True,Dataset/BATCH1000/000004_0.png,Dataset/BATCH1000/000004_1.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165996,2023-12-12 11:25:40.344616,88.130219,86.130241,87.630241,87.986328,111,111,111,111,11198,...,0.786621,0.000000,-0.005493,0.000000,True,True,255,True,Dataset/BATCH166000/165996_0.png,Dataset/BATCH166000/165996_1.png
165997,2023-12-12 11:25:40.828360,88.130219,86.130241,87.630241,87.975342,111,111,111,111,11189,...,0.786621,0.000000,-0.005493,0.000000,True,True,255,True,Dataset/BATCH166000/165997_0.png,Dataset/BATCH166000/165997_1.png
165998,2023-12-12 11:25:41.347278,88.130219,86.130241,87.630241,87.964355,111,111,111,111,11249,...,0.786621,0.000000,-0.005493,0.000000,True,True,255,True,Dataset/BATCH166000/165998_0.png,Dataset/BATCH166000/165998_1.png
165999,2023-12-12 11:25:41.871513,88.130219,86.130241,87.630241,87.953369,111,111,111,111,11215,...,0.786621,0.000000,-0.005493,0.000000,True,True,255,True,Dataset/BATCH166000/165999_0.png,Dataset/BATCH166000/165999_1.png
166000,2023-12-12 11:25:42.410629,88.130219,86.130241,87.630241,87.942383,111,111,111,111,11240,...,0.786621,0.000000,-0.005493,0.000000,True,True,255,True,Dataset/BATCH166000/166000_0.png,Dataset/BATCH166000/166000_1.png

In [43]:
df1 = pd.read_csv("FFCell_CycleManagement (4).csv") 
df1

/var/folders/05/ntvwwb8x6tdf167m58_ryr800000gn/T/ipykernel_37679/2527731139.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("FFCell_CycleManagement (4).csv")

,_time,Q_Cell_CycleCount,I_MHS_GreenRocketTray,Description,CycleState
0,2023-12-11T13:04:12.348Z,1,False,NaN,1
1,2023-12-11T13:04:12.439Z,1,False,NaN,1
2,2023-12-11T13:04:12.541Z,1,False,NaN,1
3,2023-12-11T13:04:12.637Z,1,False,NaN,1
4,2023-12-11T13:04:12.743Z,1,False,NaN,1
...,...,...,...,...,...
974831,2023-12-12T18:07:42.066Z,275,True,NoNose,21
974832,2023-12-12T18:07:42.068Z,275,True,NoNose,21
974833,2023-12-12T18:07:42.072Z,275,True,NoNose,21
974834,2023-12-12T18:07:42.282Z,275,True,NoNose,21
974835,2023-12-12T18:07:42.283Z,275,True,NoNose,21

In [44]:
# Convert _time to datetime and remove 'Z' suffix
df1['_time'] = pd.to_datetime(df1['_time']).dt.tz_localize(None)
df1 = df1[['_time', 'Description','CycleState']]
df1['_time_new'] = df1['_time'] - pd.Timedelta(hours=4,minutes=59,seconds=51,milliseconds=100)
df1

/var/folders/05/ntvwwb8x6tdf167m58_ryr800000gn/T/ipykernel_37679/4278682563.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['_time_new'] = df1['_time'] - pd.Timedelta(hours=4,minutes=59,seconds=51,milliseconds=100)

                         _time Description  CycleState               _time_new
0      2023-12-11 13:04:12.348         NaN           1 2023-12-11 08:04:21.248
1      2023-12-11 13:04:12.439         NaN           1 2023-12-11 08:04:21.339
2      2023-12-11 13:04:12.541         NaN           1 2023-12-11 08:04:21.441
3      2023-12-11 13:04:12.637         NaN           1 2023-12-11 08:04:21.537
4      2023-12-11 13:04:12.743         NaN           1 2023-12-11 08:04:21.643
...                        ...         ...         ...                     ...
974831 2023-12-12 18:07:42.066      NoNose          21 2023-12-12 13:07:50.966
974832 2023-12-12 18:07:42.068      NoNose          21 2023-12-12 13:07:50.968
974833 2023-12-12 18:07:42.072      NoNose          21 2023-12-12 13:07:50.972
974834 2023-12-12 18:07:42.282      NoNose          21 2023-12-12 13:07:51.182
974835 2023-12-12 18:07:42.283      NoNose          21 2023-12-12 13:07:51.183

[974836 rows x 4 columns]

In [45]:
# Define the start time
start_time = pd.to_datetime('2023-12-11 11:50:52.119915	')

# Filter df1 to contain rows starting from the specific timestamp
filtered_df1 = df1[df1['_time_new'] >= start_time]
filtered_df1

                         _time Description  CycleState               _time_new
71670  2023-12-11 16:50:43.255      NoNose           2 2023-12-11 11:50:52.155
71671  2023-12-11 16:50:43.339      NoNose           2 2023-12-11 11:50:52.239
71672  2023-12-11 16:50:43.440      NoNose           2 2023-12-11 11:50:52.340
71673  2023-12-11 16:50:43.539      NoNose           2 2023-12-11 11:50:52.439
71674  2023-12-11 16:50:43.638      NoNose           2 2023-12-11 11:50:52.538
...                        ...         ...         ...                     ...
974831 2023-12-12 18:07:42.066      NoNose          21 2023-12-12 13:07:50.966
974832 2023-12-12 18:07:42.068      NoNose          21 2023-12-12 13:07:50.968
974833 2023-12-12 18:07:42.072      NoNose          21 2023-12-12 13:07:50.972
974834 2023-12-12 18:07:42.282      NoNose          21 2023-12-12 13:07:51.182
974835 2023-12-12 18:07:42.283      NoNose          21 2023-12-12 13:07:51.183

[903166 rows x 4 columns]

In [46]:
filtered_df1['_time_new'] = pd.to_datetime(filtered_df1['_time_new'])
df['time'] = pd.to_datetime(df['time'])

/var/folders/05/ntvwwb8x6tdf167m58_ryr800000gn/T/ipykernel_37679/539188546.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df1['_time_new'] = pd.to_datetime(filtered_df1['_time_new'])

In [47]:
# Merge dataframes on the closest matching time values
combined_df = pd.merge_asof(df, filtered_df1, left_on='time', right_on='_time_new', direction='nearest')
combined_df

,time,Q_VFD1_Temperature,Q_VFD2_Temperature,Q_VFD3_Temperature,Q_VFD4_Temperature,M_Conv1_Speed_mmps,M_Conv2_Speed_mmps,M_Conv3_Speed_mmps,M_Conv4_Speed_mmps,I_R01_Gripper_Pot,...,I_SafetyDoor1_Status,I_SafetyDoor2_Status,Q_Cell_CycleCount,I_MHS_GreenRocketTray,Cam1,Cam2,_time,Description,CycleState,_time_new
0,2023-12-11 11:50:52.119915,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5269,...,True,True,1,True,Dataset/BATCH1000/000000_0.png,Dataset/BATCH1000/000000_1.png,2023-12-11 16:50:43.255,NoNose,2,2023-12-11 11:50:52.155
1,2023-12-11 11:50:52.483993,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5277,...,True,True,1,True,Dataset/BATCH1000/000001_0.png,Dataset/BATCH1000/000001_1.png,2023-12-11 16:50:43.539,NoNose,2,2023-12-11 11:50:52.439
2,2023-12-11 11:50:52.814902,73.130005,72.130020,73.130020,73.363525,111,83,111,111,4914,...,True,True,1,True,Dataset/BATCH1000/000002_0.png,Dataset/BATCH1000/000002_1.png,2023-12-11 16:50:43.878,NoNose,2,2023-12-11 11:50:52.778
3,2023-12-11 11:50:53.210953,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5235,...,True,True,1,True,Dataset/BATCH1000/000003_0.png,Dataset/BATCH1000/000003_1.png,2023-12-11 16:50:44.354,NoNose,2,2023-12-11 11:50:53.254
4,2023-12-11 11:50:53.554022,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5311,...,True,True,1,True,Dataset/BATCH1000/000004_0.png,Dataset/BATCH1000/000004_1.png,2023-12-11 16:50:44.656,NoNose,2,2023-12-11 11:50:53.556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165996,2023-12-12 11:25:40.344616,88.130219,86.130241,87.630241,87.986328,111,111,111,111,11198,...,True,True,255,True,Dataset/BATCH166000/165996_0.png,Dataset/BATCH166000/165996_1.png,2023-12-12 16:25:31.442,NoNose,8,2023-12-12 11:25:40.342
165997,2023-12-12 11:25:40.828360,88.130219,86.130241,87.630241,87.975342,111,111,111,111,11189,...,True,True,255,True,Dataset/BATCH166000/165997_0.png,Dataset/BATCH166000/165997_1.png,2023-12-12 16:25:31.961,NoNose,8,2023-12-12 11:25:40.861
165998,2023-12-12 11:25:41.347278,88.130219,86.130241,87.630241,87.964355,111,111,111,111,11249,...,True,True,255,True,Dataset/BATCH166000/165998_0.png,Dataset/BATCH166000/165998_1.png,2023-12-12 16:25:32.457,NoNose,8,2023-12-12 11:25:41.357
165999,2023-12-12 11:25:41.871513,88.130219,86.130241,87.630241,87.953369,111,111,111,111,11215,...,True,True,255,True,Dataset/BATCH166000/165999_0.png,Dataset/BATCH166000/165999_1.png,2023-12-12 16:25:32.953,NoNose,8,2023-12-12 11:25:41.853
166000,2023-12-12 11:25:42.410629,88.130219,86.130241,87.630241,87.942383,111,111,111,111,11240,...,True,True,255,True,Dataset/BATCH166000/166000_0.png,Dataset/BATCH166000/166000_1.png,2023-12-12 16:25:33.541,NoNose,8,2023-12-12 11:25:42.441

In [48]:
combined_df.to_csv('FF_Data_COMBINED_TEST.csv')

In [49]:
combined_df

,time,Q_VFD1_Temperature,Q_VFD2_Temperature,Q_VFD3_Temperature,Q_VFD4_Temperature,M_Conv1_Speed_mmps,M_Conv2_Speed_mmps,M_Conv3_Speed_mmps,M_Conv4_Speed_mmps,I_R01_Gripper_Pot,...,I_SafetyDoor1_Status,I_SafetyDoor2_Status,Q_Cell_CycleCount,I_MHS_GreenRocketTray,Cam1,Cam2,_time,Description,CycleState,_time_new
0,2023-12-11 11:50:52.119915,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5269,...,True,True,1,True,Dataset/BATCH1000/000000_0.png,Dataset/BATCH1000/000000_1.png,2023-12-11 16:50:43.255,NoNose,2,2023-12-11 11:50:52.155
1,2023-12-11 11:50:52.483993,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5277,...,True,True,1,True,Dataset/BATCH1000/000001_0.png,Dataset/BATCH1000/000001_1.png,2023-12-11 16:50:43.539,NoNose,2,2023-12-11 11:50:52.439
2,2023-12-11 11:50:52.814902,73.130005,72.130020,73.130020,73.363525,111,83,111,111,4914,...,True,True,1,True,Dataset/BATCH1000/000002_0.png,Dataset/BATCH1000/000002_1.png,2023-12-11 16:50:43.878,NoNose,2,2023-12-11 11:50:52.778
3,2023-12-11 11:50:53.210953,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5235,...,True,True,1,True,Dataset/BATCH1000/000003_0.png,Dataset/BATCH1000/000003_1.png,2023-12-11 16:50:44.354,NoNose,2,2023-12-11 11:50:53.254
4,2023-12-11 11:50:53.554022,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5311,...,True,True,1,True,Dataset/BATCH1000/000004_0.png,Dataset/BATCH1000/000004_1.png,2023-12-11 16:50:44.656,NoNose,2,2023-12-11 11:50:53.556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165996,2023-12-12 11:25:40.344616,88.130219,86.130241,87.630241,87.986328,111,111,111,111,11198,...,True,True,255,True,Dataset/BATCH166000/165996_0.png,Dataset/BATCH166000/165996_1.png,2023-12-12 16:25:31.442,NoNose,8,2023-12-12 11:25:40.342
165997,2023-12-12 11:25:40.828360,88.130219,86.130241,87.630241,87.975342,111,111,111,111,11189,...,True,True,255,True,Dataset/BATCH166000/165997_0.png,Dataset/BATCH166000/165997_1.png,2023-12-12 16:25:31.961,NoNose,8,2023-12-12 11:25:40.861
165998,2023-12-12 11:25:41.347278,88.130219,86.130241,87.630241,87.964355,111,111,111,111,11249,...,True,True,255,True,Dataset/BATCH166000/165998_0.png,Dataset/BATCH166000/165998_1.png,2023-12-12 16:25:32.457,NoNose,8,2023-12-12 11:25:41.357
165999,2023-12-12 11:25:41.871513,88.130219,86.130241,87.630241,87.953369,111,111,111,111,11215,...,True,True,255,True,Dataset/BATCH166000/165999_0.png,Dataset/BATCH166000/165999_1.png,2023-12-12 16:25:32.953,NoNose,8,2023-12-12 11:25:41.853
166000,2023-12-12 11:25:42.410629,88.130219,86.130241,87.630241,87.942383,111,111,111,111,11240,...,True,True,255,True,Dataset/BATCH166000/166000_0.png,Dataset/BATCH166000/166000_1.png,2023-12-12 16:25:33.541,NoNose,8,2023-12-12 11:25:42.441

In [50]:
df=combined_df
# Create a new column to store the continuous values
df['Cycle_State_New'] = df['Q_Cell_CycleCount']

# Initialize the offset
offset = 0
count=0
# Loop through the DataFrame and adjust the values
for i in range(1, len(df)):
    if df.loc[i, 'Q_Cell_CycleCount'] == 0:
        offset = df.loc[i - 1, 'Cycle_State_New']
        count+=1
        df.loc[i, 'Description'] = 'E_STOPPED' 
    df.loc[i, 'Cycle_State_New'] += offset  
    
df

,time,Q_VFD1_Temperature,Q_VFD2_Temperature,Q_VFD3_Temperature,Q_VFD4_Temperature,M_Conv1_Speed_mmps,M_Conv2_Speed_mmps,M_Conv3_Speed_mmps,M_Conv4_Speed_mmps,I_R01_Gripper_Pot,...,I_SafetyDoor2_Status,Q_Cell_CycleCount,I_MHS_GreenRocketTray,Cam1,Cam2,_time,Description,CycleState,_time_new,Cycle_State_New
0,2023-12-11 11:50:52.119915,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5269,...,True,1,True,Dataset/BATCH1000/000000_0.png,Dataset/BATCH1000/000000_1.png,2023-12-11 16:50:43.255,NoNose,2,2023-12-11 11:50:52.155,1
1,2023-12-11 11:50:52.483993,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5277,...,True,1,True,Dataset/BATCH1000/000001_0.png,Dataset/BATCH1000/000001_1.png,2023-12-11 16:50:43.539,NoNose,2,2023-12-11 11:50:52.439,1
2,2023-12-11 11:50:52.814902,73.130005,72.130020,73.130020,73.363525,111,83,111,111,4914,...,True,1,True,Dataset/BATCH1000/000002_0.png,Dataset/BATCH1000/000002_1.png,2023-12-11 16:50:43.878,NoNose,2,2023-12-11 11:50:52.778,1
3,2023-12-11 11:50:53.210953,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5235,...,True,1,True,Dataset/BATCH1000/000003_0.png,Dataset/BATCH1000/000003_1.png,2023-12-11 16:50:44.354,NoNose,2,2023-12-11 11:50:53.254,1
4,2023-12-11 11:50:53.554022,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5311,...,True,1,True,Dataset/BATCH1000/000004_0.png,Dataset/BATCH1000/000004_1.png,2023-12-11 16:50:44.656,NoNose,2,2023-12-11 11:50:53.556,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165996,2023-12-12 11:25:40.344616,88.130219,86.130241,87.630241,87.986328,111,111,111,111,11198,...,True,255,True,Dataset/BATCH166000/165996_0.png,Dataset/BATCH166000/165996_1.png,2023-12-12 16:25:31.442,NoNose,8,2023-12-12 11:25:40.342,285
165997,2023-12-12 11:25:40.828360,88.130219,86.130241,87.630241,87.975342,111,111,111,111,11189,...,True,255,True,Dataset/BATCH166000/165997_0.png,Dataset/BATCH166000/165997_1.png,2023-12-12 16:25:31.961,NoNose,8,2023-12-12 11:25:40.861,285
165998,2023-12-12 11:25:41.347278,88.130219,86.130241,87.630241,87.964355,111,111,111,111,11249,...,True,255,True,Dataset/BATCH166000/165998_0.png,Dataset/BATCH166000/165998_1.png,2023-12-12 16:25:32.457,NoNose,8,2023-12-12 11:25:41.357,285
165999,2023-12-12 11:25:41.871513,88.130219,86.130241,87.630241,87.953369,111,111,111,111,11215,...,True,255,True,Dataset/BATCH166000/165999_0.png,Dataset/BATCH166000/165999_1.png,2023-12-12 16:25:32.953,NoNose,8,2023-12-12 11:25:41.853,285
166000,2023-12-12 11:25:42.410629,88.130219,86.130241,87.630241,87.942383,111,111,111,111,11240,...,True,255,True,Dataset/BATCH166000/166000_0.png,Dataset/BATCH166000/166000_1.png,2023-12-12 16:25:33.541,NoNose,8,2023-12-12 11:25:42.441,285

In [51]:
df = df.drop(['_time'], axis=1)

In [52]:
distinct_counts = combined_df['Description'].value_counts().reset_index()
distinct_counts.columns = ['Description', 'count']
distinct_counts

              Description  count
0  NoNose,NoBody2,NoBody1  31422
1          NoNose,NoBody2  30202
2                  NoNose  23829
3               E_STOPPED     69

In [55]:
df

,time,Q_VFD1_Temperature,Q_VFD2_Temperature,Q_VFD3_Temperature,Q_VFD4_Temperature,M_Conv1_Speed_mmps,M_Conv2_Speed_mmps,M_Conv3_Speed_mmps,M_Conv4_Speed_mmps,I_R01_Gripper_Pot,...,M_R04_TJointAngle_Degree,I_SafetyDoor1_Status,I_SafetyDoor2_Status,Q_Cell_CycleCount,I_MHS_GreenRocketTray,Cam1,Cam2,Description,CycleState,Cycle_State_New
0,2023-12-11 11:50:52.119915,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5269,...,0.004302,True,True,1,True,Dataset/BATCH1000/000000_0.png,Dataset/BATCH1000/000000_1.png,NoNose,2,1
1,2023-12-11 11:50:52.483993,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5277,...,0.004302,True,True,1,True,Dataset/BATCH1000/000001_0.png,Dataset/BATCH1000/000001_1.png,NoNose,2,1
2,2023-12-11 11:50:52.814902,73.130005,72.130020,73.130020,73.363525,111,83,111,111,4914,...,0.004302,True,True,1,True,Dataset/BATCH1000/000002_0.png,Dataset/BATCH1000/000002_1.png,NoNose,2,1
3,2023-12-11 11:50:53.210953,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5235,...,0.004302,True,True,1,True,Dataset/BATCH1000/000003_0.png,Dataset/BATCH1000/000003_1.png,NoNose,2,1
4,2023-12-11 11:50:53.554022,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5311,...,0.004302,True,True,1,True,Dataset/BATCH1000/000004_0.png,Dataset/BATCH1000/000004_1.png,NoNose,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165996,2023-12-12 11:25:40.344616,88.130219,86.130241,87.630241,87.986328,111,111,111,111,11198,...,0.000000,True,True,255,True,Dataset/BATCH166000/165996_0.png,Dataset/BATCH166000/165996_1.png,NoNose,8,285
165997,2023-12-12 11:25:40.828360,88.130219,86.130241,87.630241,87.975342,111,111,111,111,11189,...,0.000000,True,True,255,True,Dataset/BATCH166000/165997_0.png,Dataset/BATCH166000/165997_1.png,NoNose,8,285
165998,2023-12-12 11:25:41.347278,88.130219,86.130241,87.630241,87.964355,111,111,111,111,11249,...,0.000000,True,True,255,True,Dataset/BATCH166000/165998_0.png,Dataset/BATCH166000/165998_1.png,NoNose,8,285
165999,2023-12-12 11:25:41.871513,88.130219,86.130241,87.630241,87.953369,111,111,111,111,11215,...,0.000000,True,True,255,True,Dataset/BATCH166000/165999_0.png,Dataset/BATCH166000/165999_1.png,NoNose,8,285
166000,2023-12-12 11:25:42.410629,88.130219,86.130241,87.630241,87.942383,111,111,111,111,11240,...,0.000000,True,True,255,True,Dataset/BATCH166000/166000_0.png,Dataset/BATCH166000/166000_1.png,NoNose,8,285

In [56]:
import pandas as pd


# Initialize the 'actual_state' column with 'normal'
df['actual_state'] = 'Normal'

# Define a function to update actual_state based on conditions
def update_actual_state(group):
    anomaly = group['Description'].iloc[0]
    
    if anomaly == 'E_STOPPED':
        group['actual_state'] = 'E_STOPPED'
        
    elif anomaly == 'NoNose':
        group.loc[group['CycleState'].between(8, 21), 'actual_state'] = 'NoNose'
    
    elif anomaly == 'NoNose,NoBody2':
        group.loc[group['CycleState'].between(6, 8), 'actual_state'] = 'NoBody2'
        group.loc[group['CycleState'].between(8, 21), 'actual_state'] = 'NoNose,NoBody2'
        
    elif anomaly == 'NoNose,NoBody2,NoBody1':
        group.loc[group['CycleState'].between(4, 6), 'actual_state'] = 'NoBody1'
        group.loc[group['CycleState'].between(6, 8), 'actual_state'] = 'NoBody2,NoBody1'
        group.loc[group['CycleState'].between(8, 21), 'actual_state'] = 'NoNose,NoBody2,NoBody1'
        
    
    
    return group

# Apply the function to each group based on 'cycle_count'
df = df.groupby('Cycle_State_New').apply(update_actual_state)

# Display the updated DataFrame
df

,time,Q_VFD1_Temperature,Q_VFD2_Temperature,Q_VFD3_Temperature,Q_VFD4_Temperature,M_Conv1_Speed_mmps,M_Conv2_Speed_mmps,M_Conv3_Speed_mmps,M_Conv4_Speed_mmps,I_R01_Gripper_Pot,...,I_SafetyDoor1_Status,I_SafetyDoor2_Status,Q_Cell_CycleCount,I_MHS_GreenRocketTray,Cam1,Cam2,Description,CycleState,Cycle_State_New,actual_state
0,2023-12-11 11:50:52.119915,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5269,...,True,True,1,True,Dataset/BATCH1000/000000_0.png,Dataset/BATCH1000/000000_1.png,NoNose,2,1,Normal
1,2023-12-11 11:50:52.483993,73.130005,72.130020,73.130020,73.363525,111,83,111,111,5277,...,True,True,1,True,Dataset/BATCH1000/000001_0.png,Dataset/BATCH1000/000001_1.png,NoNose,2,1,Normal
2,2023-12-11 11:50:52.814902,73.130005,72.130020,73.130020,73.363525,111,83,111,111,4914,...,True,True,1,True,Dataset/BATCH1000/000002_0.png,Dataset/BATCH1000/000002_1.png,NoNose,2,1,Normal
3,2023-12-11 11:50:53.210953,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5235,...,True,True,1,True,Dataset/BATCH1000/000003_0.png,Dataset/BATCH1000/000003_1.png,NoNose,2,1,Normal
4,2023-12-11 11:50:53.554022,73.130005,72.130020,73.130020,73.352539,111,83,111,111,5311,...,True,True,1,True,Dataset/BATCH1000/000004_0.png,Dataset/BATCH1000/000004_1.png,NoNose,2,1,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165996,2023-12-12 11:25:40.344616,88.130219,86.130241,87.630241,87.986328,111,111,111,111,11198,...,True,True,255,True,Dataset/BATCH166000/165996_0.png,Dataset/BATCH166000/165996_1.png,NoNose,8,285,NoNose
165997,2023-12-12 11:25:40.828360,88.130219,86.130241,87.630241,87.975342,111,111,111,111,11189,...,True,True,255,True,Dataset/BATCH166000/165997_0.png,Dataset/BATCH166000/165997_1.png,NoNose,8,285,NoNose
165998,2023-12-12 11:25:41.347278,88.130219,86.130241,87.630241,87.964355,111,111,111,111,11249,...,True,True,255,True,Dataset/BATCH166000/165998_0.png,Dataset/BATCH166000/165998_1.png,NoNose,8,285,NoNose
165999,2023-12-12 11:25:41.871513,88.130219,86.130241,87.630241,87.953369,111,111,111,111,11215,...,True,True,255,True,Dataset/BATCH166000/165999_0.png,Dataset/BATCH166000/165999_1.png,NoNose,8,285,NoNose
166000,2023-12-12 11:25:42.410629,88.130219,86.130241,87.630241,87.942383,111,111,111,111,11240,...,True,True,255,True,Dataset/BATCH166000/166000_0.png,Dataset/BATCH166000/166000_1.png,NoNose,8,285,NoNose

In [60]:
df['actual_state'].value_counts()

Normal                    90844
NoNose,NoBody2,NoBody1    26628
NoNose,NoBody2            25206
NoNose                    19307
NoBody1                    1849
NoBody2,NoBody1            1089
NoBody2                    1078
Name: actual_state, dtype: int64

In [17]:
df.to_csv('FF_Data_New.csv')

In [18]:
import pandas as pd

# Assuming df is your DataFrame
columns = df.columns.tolist()
columns_string = ','.join(f"'{col}'" for col in columns)
print(columns_string)

'time','Q_VFD1_Temperature','Q_VFD2_Temperature','Q_VFD3_Temperature','Q_VFD4_Temperature','M_Conv1_Speed_mmps','M_Conv2_Speed_mmps','M_Conv3_Speed_mmps','M_Conv4_Speed_mmps','I_R01_Gripper_Pot','I_R01_Gripper_Load','I_R02_Gripper_Pot','I_R02_Gripper_Load','I_R03_Gripper_Pot','I_R03_Gripper_Load','I_R04_Gripper_Pot','I_R04_Gripper_Load','M_R01_SJointAngle_Degree','M_R01_LJointAngle_Degree','M_R01_UJointAngle_Degree','M_R01_RJointAngle_Degree','M_R01_BJointAngle_Degree','M_R01_TJointAngle_Degree','M_R02_SJointAngle_Degree','M_R02_LJointAngle_Degree','M_R02_UJointAngle_Degree','M_R02_RJointAngle_Degree','M_R02_BJointAngle_Degree','M_R02_TJointAngle_Degree','M_R03_SJointAngle_Degree','M_R03_LJointAngle_Degree','M_R03_UJointAngle_Degree','M_R03_RJointAngle_Degree','M_R03_BJointAngle_Degree','M_R03_TJointAngle_Degree','M_R04_SJointAngle_Degree','M_R04_LJointAngle_Degree','M_R04_UJointAngle_Degree','M_R04_RJointAngle_Degree','M_R04_BJointAngle_Degree','M_R04_TJointAngle_Degree','I_SafetyDoor1_Status','I_SafetyDoor2_Status','Q_Cell_CycleCount','I_MHS_GreenRocketTray','Cam1','Cam2','_time','Description','CycleState','_time_new','Cycle_State_New','actual_state'